### ISSUE TITLE
DBSCAN algorithm

### ISSUE THREAD

**Issue by 0link87** [mdsatria/npc_digital_tils#1]
Hello, I have a question to ask. In the model where the DBSCAN algorithm is used to cluster tumor cell nuclei based on density, when analyzing each WSI (Whole Slide Image), are the parameters consistent across all WSIs, or are they adjusted according to each WSI?

**Comment by mdsatria** [comment]
Hi @0link87, thank you for your interest in our work.
We use consistent parameters for DBSCAN across all WSIs in our dataset. These parameters were defined in empirical manner.

I hope this answers your question.

**Comment by 0link87** [comment]
Thank you for your answer
